### ISSUE TITLE
Wrong URL for website

### ISSUE THREAD

**Issue by Mazwak** [flathub/net.minetest.Minetest#12]
The current URL is "minetest.net".

The right URL is "www.minetest.net".

I don't know where it comes from, so I'm opening the issue here.

**Comment by Calinou** [comment]
The website URL is defined in the AppStream metadata file, which is part of the Minetest repository: https://github.com/minetest/minetest/blob/master/misc/net.minetest.minetest.appdata.xml#L47

Please submit a pull request there, while also updating URLs to use HTTPS :slightly_smiling_face:
