### ISSUE TITLE
flathubbot: FAILURE

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/net.minetest.Minetest#14]
https://flathub.org/builds/#/builders/32/builds/5767
```
builddir/files/share/appdata/net.minetest.Minetest.appdata.xml: FAILED:
• tag-missing           : <content_rating> required [use https://odrs.gnome.org/oars]
Validation of files failed
```

**Comment by Calinou** [comment]
`<content_rating>` information has been added to the [AppStream metadata in the `master` branch](https://github.com/minetest/minetest/blob/master/misc/net.minetest.minetest.appdata.xml), I guess you could download it as a file in the manifest.

**Comment by Calinou** [comment]
This should be fixed by https://github.com/flathub/net.minetest.Minetest/pull/16, thanks to upstream changes.
