### ISSUE TITLE
Screenshots taken in Minetest are never written to a file

### ISSUE THREAD

**Issue by ElonSatoshi** [flathub/net.minetest.Minetest#17]
How to reproduce:

1. `flatpak run net.minetest.Minetest`
2. Start a game of Minetest, hit f12
3. It will say "Saved screenshot to './screenshot_<date>_<time>.png'"
4. Run `find ~/ | grep screenshot_<date>_<time>.png`.
5. If you want to be extra sure, run `sudo find / | grep screenshot_<date>_<time>.png`.

Expected result: You find the screenshot somewhere on your computer

Actual result: The screenshot is nowhere to be found.

Recommended fix: Change minetest's default screenshot directory to something that the flatpak has write access to.

**Comment by Calinou** [comment]
Pull request opened upstream: https://github.com/minetest/minetest/pull/9122

**Comment by Calinou** [comment]
https://github.com/minetest/minetest/pull/9122 was merged, this should be fixed once the next Minetest version is released (and this Flatpak updated).

**Comment by skibur** [comment]
Thanks for the merge.
