### ISSUE TITLE
Flatpaked Minetest uses an older OpenGL version than native package

### ISSUE THREAD

**Issue by andrenete** [flathub/net.minetest.Minetest#27]
I'm using Fedora Silverblue 33 and noticed that flatpaked Minetest uses OpenGL version 3.0 while the native (layered) package uses 4.6.

However, running it manually with `flatpak run --env='MESA_GL_VERSION_OVERRIDE=4.6' net.minetest.Minetest --verbose` works, and in the terminal I can see that Irrlicht is really using version 4.6: `INFO[Main]: Irrlicht: Using renderer: OpenGL 4.6`.

**Comment by Calinou** [comment]
This is because Mesa drivers only expose OpenGL 3.0 if the application uses the OpenGL compatibility profile (instead of the core profile).

This should generally not have any performance implications, so I'm not sure if it's worth solving unless the solution is trivial.

**Comment by Calinou** [comment]
Since I believe this is done by design in older Mesa versions, there's nothing we can do about this on our end (at least until a newer FreeDesktop runtime is released).
