### ISSUE TITLE
gnome-software reports that Minetest license is proprietary

### ISSUE THREAD

**Issue by akozlovskiy119** [flathub/net.minetest.Minetest#32]
I believe Minetest is Free software? Minetest repository appdata file (`misc/net.minetest.minetest.appdata.xml`) contains:
```xml
<project_license>LGPL-2.1+ and CC-BY-SA-3.0 and MIT and Apache-2.0</project_license>
```

Screenshot from gnome-software:
![Снимок экрана от 2021-07-05 22-23-16](https://user-images.githubusercontent.com/22382143/124511795-a2943700-dddf-11eb-9871-c7b83336289c.png)

**Comment by akozlovskiy119** [comment]
According to https://spdx.org/licenses/:
- `LGPL-2.1+` considered deprecated
- `CC-BY-SA-3.0` is not considered free license by FSF and not approved by OSI either, it seems to be the main problem

**Comment by Calinou** [comment]
I've never understood the logic for GNOME Software marking things as proprietary. Is this something we can even fix on our end?

**Comment by Calinou** [comment]
I guess we can list only the source code licenses to fix this.

**Comment by akozlovskiy119** [comment]
Appstream uses [`spdx-free-license-ids.txt`](https://github.com/ximion/appstream/blob/master/data/spdx-free-license-ids.txt) file to [check if license is free](https://github.com/ximion/appstream/blob/c2c78260ec3da325daeb2c6dede87f79eed0ab2c/src/as-spdx.c#L717). Yes, there are a lot of bugs related to specifying licenses not in this list, like `CC-BY-SA-3.0`, for example in [GNOME Mahjongg](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1200).

>  we can list only the source code licenses

Seems like the right answer. This is what [devs suggest](https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1200#note_1076399) for Mahjongg, for example.

**Comment by akozlovskiy119** [comment]
Actually, this is clearly stated in appstream docs now: https://github.com/ximion/appstream/blob/c2c78260ec3da325daeb2c6dede87f79eed0ab2c/docs/xml/metainfo-component.xml#L1084

**Comment by astrosticks** [comment]
Gnome Software now displays the license in a favorable light. Time to close this issue?

![Screenshot from 2022-02-02 12-53-23](https://user-images.githubusercontent.com/32315760/152218918-945b4b1e-d1dd-46f1-9c1a-d15891d2bb44.png)
