### ISSUE TITLE
5.5.0 crash on launch

### ISSUE THREAD

**Issue by astrosticks** [flathub/net.minetest.Minetest#35]
Just installed from Flathub Stable using Gnome Software on Fedora 35. App crashes immediately. I am on Wayland with Pipewire and latest NVIDIA Graphics.

`flatpak run net.minetest.Minetest`:
```
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
2022-02-02 13:01:38: WARNING[Main]: Irrlicht: No doublebuffering available.
```

`flatpak info net.minetest.Minetest`
```
Minetest - Multiplayer infinite-world block sandbox game

          ID: net.minetest.Minetest
         Ref: app/net.minetest.Minetest/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 5.5.0
     License: LGPL-2.1+ and CC-BY-SA-3.0 and MIT and Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 29.4 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: fffcb14a4f6cda135d4f111399bf9669f38c559c16061f37dab3f2fce41ea603
      Parent: 73f448a59aa3768d073aee8f38ca72f5c2c9dc79ff6d38a9b702f5630c6d7f1c
     Subject: Bump the runtime 21.08 and new Irrlicht (irrlichtmt) (#34) (bae53fb3)
        Date: 2022-01-31 17:27:19 +0000
```

Editing various permissions in Flatseal doesn't seem to affect anything.

I understand there's not a lot to go off of here, so any suggestions for what else to try/add to figure this issue out would be appreciated.

**Comment by Calinou** [comment]
I get a feeling this is Wayland-specific, as I can't reproduce this on Fedora 34 with NVIDIA 495.46 and KDE X11.

**Comment by astrosticks** [comment]
I just spun up a Debian 11 VM with Wayland and the flatpak launches with no problems. 
`gnome-shell 3.38.6-1~deb11u1`

**Comment by astrosticks** [comment]
Weird. This app was crashing at launch along with a bunch of other flatpaks I had installed recently, but since then, after rebooting, they launch fine now. It may possibly be a bug with Flatpak itself. Since I can't reproduce it anymore I'll close this.
