### ISSUE TITLE
Change the luajit to lua

### ISSUE THREAD

**Issue by farribeiro** [flathub/net.minetest.Minetest#42]
I looking that LuaJIT (A beta released in 2019) although it is functional is lain compared to the Lua (Stable version released in January 2022). 

Would it be interesting to update this dependency?

**Comment by Calinou** [comment]
LuaJIT is much faster than Lua. Even if it's older, we should keep it in the Flatpak to reduce CPU usage in singleplayer.

**Comment by farribeiro** [comment]
I'll close the issue as resolved. 

PS: Could we convince the team to release a stable version with the latest LuaJIT commit?
