### ISSUE TITLE
GTK4/libadwaita titlebar

### ISSUE THREAD

**Issue by julianfairfax** [flathub/net.minetest.Minetest#49]
I don't know how this stuff works for Minetest; what toolkit it uses for the UI and such, but it would be nice if it was possible to use a GTK4/libadwaita titlebar, so that it would look at home on modern GNOME.

**Comment by Calinou** [comment]
Mientest uses [IrrlichtMt](https://github.com/minetest/irrlicht), but doesn't use GTK/Qt or even SDL. Using libadwaita is out of scope for it, as IrrlichtMt intends to remain minimal in terms of dependencies.

**Comment by Calinou** [comment]
I don't think GTK titlebar theming in Flatpaks is something we have control over. You do have a way to install Flatpak GTK theme packages (e.g. Breeze/Breeze Dark when using KDE), but I'm not sure how you make them the default.

**Comment by sfan5** [comment]
While SDL2 support (mostly) works it is still in the testing stage, please don't ship that to users in a release build.
